name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install system dependencies for native modules
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 g++ make

      - name: Clean node_modules and caches
        run: |
          rm -rf node_modules
          rm -rf apps/api/node_modules
          pnpm store prune

      - name: Install dependencies
        run: pnpm install

      - name: Build shared packages
        run: pnpm build:packages

      - name: Rebuild bcrypt inside API workspace
        working-directory: apps/api
        run: pnpm rebuild bcrypt

      - name: Lint API
        run: pnpm lint:api

      - name: Run API unit tests
        run: pnpm api:test:cov

      - name: Run API e2e tests
        run: pnpm api:test:e2e
